export const LIMITS = {
  CATEGORIES_LIMITS: 15,
  PRODUCTS_LIMITS: 12,
  RELATED_PRODUCTS_LIMITS: 20,
  BEST_SELLER_PRODUCTS_LIMITS: 8,
  POPULAR_PRODUCTS_LIMITS: 8,
  LATEST_BLOG_LIMITS: 3,

  POPULAR_PICKS_LIMITS: 4,
};
